### PR TITLE
Add Portuguese (Portugal) translation.

### PR DESCRIPTION
**Pull request by jcalado**
Adds the i18n file for a Portuguese translation.

### CODE REVIEW

**Comment by marcandre** [comment]
Looks good, but shouldn't the key be `pt` instead of `pt-pt`?

**Comment by marcandre** [comment]
Ping @jcalado ?

**Comment by marcandre** [comment]
Oh, I see, there's a 'pt-br' translation already. Deifnitely not sure we need two translations for this, but merged anyways. Thanks

**Comment by claudiomedina** [comment]
pt-br is for brasilian portuguese (https://en.wikipedia.org/wiki/Brazilian_Portuguese) that has some different terms.

**Pull request closed without merging**
