### PR TITLE
Custom validator messages with compound names (via validator#addMessage)

### PR DESCRIPTION
**Pull request by alampros**
Add tests for custom error messages without using data attributes (using validator#addMessage).

May be related to #806

The bug can be seen in this [jsfiddle](http://jsfiddle.net/alampros/dknc3nfk/).

### CODE REVIEW

**Comment by marcandre** [comment]
Awesome PR, thanks so much!

What would you think of DRYing up a bit the new tests, either combining them or putting the common setup in a function?

**Comment by alampros** [comment]
Sure thing. I can just remove some repeated setup.

**Comment by marcandre** [comment]
Mmm, thanks for modifying your PR, but I feel tests should be independent, it's a really bad idea to rely on side effects from another test.

**Comment by alampros** [comment]
You're quite welcome, and I couldn't agree more. This feels like it should be done in setup/teardown (`before()` and `after()` in should.js terms) functions, but that would mean putting these tests in their own suite, right? Perhaps a nested suite?

**Comment by marcandre** [comment]
I think you can nest tests (with their setup/teardown).

I'm also fine if you want to test both as in the same test, they're really about the same thing.

**Comment by alampros** [comment]
Anything else I can do on this?

**Comment by marcandre** [comment]
Oh, sorry, didn't see you had made the changes.

Looking good.

I think if you remove the references to `done` and squash the commits, we'll be good to go :smile:

**Comment by marcandre** [comment]
All fixed now. Thanks!

**Pull request closed without merging**
