### PR TITLE
data-parsley-class-handler can now contain a global function name

### PR DESCRIPTION
**Pull request by benjaminpick**
Currently, the class handler function can only be specified as JS code:

``` js
$('#element').psly({
      classHandler: function (field) {
        return $('#field3');
      }
});
```

With this minor addition, global functions can be named in the data-attribute:

``` js
function parsleyClassHandler(field) {
        return $('#field3');
}
```

``` html
<input type="text" data-parsley-class-handler="parsleyClassHandler" required />
```

(Sorry I feel quite at loss using gulp etc. I probably need to execute the build somehow and let the test suite run, could you please add this to your CONTRIBUTING.md?)

### CODE REVIEW

**Comment by benjaminpick** [comment]
No idea why the travis build errors. Locally only the tests mentioned in #1095 fail

**Comment by marcandre** [comment]
Thanks a lot for the PR.

I've improved the CONTRIBUTING file, I hope this clears things up.

The PR is a good start, but there are a couple of things that need to be fixed. Are you're willing to address them?
- ideally, that feature should work for any option that accepts a function callback, not just `classHandler`.
- best not to remove the functionality of accepting a direct jQuery set (even though I think it's untested and undocumented). See http://stackoverflow.com/questions/1853223/check-if-object-is-a-jquery-object
- this should probably be all one commit (squash them).
- doc needs updating
- not sure if it wouldn't be best to make separate tests instead of modifying existing ones.

**Comment by benjaminpick** [comment]
* This only concerns `data-parsley-errors-container` right? `data-parsley-value` would need a new data name to avoid ambiguous situations.
* I don't think specifying the jQuery object worked before (`this.options.classHandler.call` would error). 
* AFAIK you now can squash the commits automatically when you merge the pull request (see https://github.com/blog/2141-squash-your-commits).

**Comment by marcandre** [comment]
* Yeah, probably there's only `errorsContainer` too.

* The `return` was before any `this.options.classHandler.call` I think...

* ok

**Comment by benjaminpick** [comment]
I have started to update the docu but I think it is best to let you finish this, you know better which parts of it need editing ... 

(You need to update the link to Contributing.md in the Readme.md)

**Comment by benjaminpick** [comment]
I am getting concerns that this is also a kind of of `eval` and thus potentially enabling XSS. 

For example, the Typo3 function `GeneralUtility::removeXSS` only destroys a blacklist of HTML tags & attributes, this attribute would be left as-is. Now imagine the site has a JS function called `permanentlyDeleteAccount` that doesn't take a parameter, and some other minor flaws somewhere, and together it would be a viable XSS attack.

What do you think?

**Comment by marcandre** [comment]
Oh oh, I dropped the ball on this one, sorry. Finally merged.
Thanks again for the good work!

**Comment by marcandre** [comment]
BTW, @benjaminpick contact me if you'd be interested in commit access to Parsley.

**Comment by benjaminpick** [comment]
I feel honored, but I will politely decline ... because I have the feeling that the code is so complex I wouldn't commit anything without discussing it with you.

**Pull request closed without merging**
