### PR TITLE
Add Albanian translation.

### PR DESCRIPTION
**Pull request by ermand**
Add Albanian translation.

### CODE REVIEW

**Comment by marcandre** [comment]
Great!

Would you mind squashing your two commits, since the last one is just a fix for the previous one?

**Comment by ermand** [comment]
Squashing of 2 commits is done.

**Comment by marcandre** [comment]
I'm seeing 4 commits...

I think `git reset master && git add . && git commit -m "Add Albanian translation" && git push -f` should fix it all. If you're too lost I can do it myself, just let me know.

Thanks

**Comment by ermand** [comment]
I tried with: `git reset master && git add . && git commit -m "Add Albanian translation" && git push -f` but still its showing 4 commits. If you can please do it.

Thanks

**Comment by marcandre** [comment]
Merged as 64328b765a

Thanks for the PR!

**Comment by marcandre** [comment]
PS: I should have mentioned you had to be in your branch...

**Comment by ermand** [comment]
Ok, great. Thanks :)

**Pull request closed without merging**
