### PR TITLE
Added scenario and removed lowercase of constraint name.

### PR DESCRIPTION
**Pull request by jalandis**
Added support for custom validator messages with hyphens.

Addresses issue #805 

  220 tests complete (954 ms)
  1 test pending

### CODE REVIEW

**Comment by marcandre** [comment]
Looks like a great PR to me.
I doubled checked if there was a valid reason for the `toLowercase` to be there and couldn't find anything. It dates from the first code iteration too.
If I don't hear scream from @guillaumepotier I'll merge this in a couple of days.

**Comment by guillaumepotier** [comment]
I chose originally to lowercase to avoid user typo and ensure that data-Required matched correctly required constraint. Dunno if it is excessive or not. Since it seems more limiting than handy we could try to ship it in 2.1. But it would be BC Break for some users that left case typo.

**Comment by marcandre** [comment]
That's what I thought (avoiding errors).
Sounds good for 2.1 then.

**Comment by marcandre** [comment]
@jalandis If you want to make your PR perfect, you could:
* make the test case title more explicit about compound name
* rebase it off the 2.1 branch.
* modify the CHANGELOG

**Comment by guillaumepotier** [comment]
:+1:

**Comment by marcandre** [comment]
Merged. Thanks so much for the PR, it's much appreciated!

**Pull request closed without merging**
