### PR TITLE
Issue 916 kludge

### PR DESCRIPTION
**Pull request by JanezStupar**
This is a PR for issue #916. It is a kludge-y approach to fixing a race condition that happens when remote validators are used on fields which also utilize local validation (remote validation fails, displays error message -> parsley binds validation to keyup event) -> which leads to situation where error message gets hidden immediately after triggered by 'enter' keyup.

The issue is resolved by surpressing keyup handler, whenever it is triggered by Enter keyup event (no need to validate on enter keypress).

### CODE REVIEW

**Comment by marcandre** [comment]
Thanks a lot for the PR.
I'm actively working on a change on handling validations (remote and local) using promises which I hope would resolve the issue by itself. I'll keep this opened to check in case it doesn't though.

**Comment by JanezStupar** [comment]
@marcandre that is great news. I feel your approach is the correct way to go.

**Comment by jayepoch** [comment]
Thanks for your help on this guys! Experiencing this bug too & wondering how the fix might be coming, @marcandre? Anything we can help with?

**Comment by marcandre** [comment]
>  Anything we can help with?

Yes! Haven't had time to check it out, but anyone can try out the v2.2.0rc1 release and let me know if the issue is still there or not... :smile:

**Comment by jayepoch** [comment]
Thanks Marc! We tried RC1 but it unfortunately broke some aspects of our
validation process, so we're using the kludge fix for now

On Mon, Aug 17, 2015 at 4:13 PM, Marc-André Lafortune <
notifications@github.com> wrote:

> Anything we can help with?
>
> Yes! Haven't had time to check it out, but anyone can try out the
> v2.2.0rc1 release and let me know if the issue is still there or not... [image:
> :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guillaumepotier/Parsley.js/pull/921#issuecomment-131989100>
> .
>



-- 
Jason Wohlstadter
CEO, Proton
sndsystm.com/+

**Comment by marcandre** [comment]
> Thanks Marc! We tried RC1 but it unfortunately broke some aspects of our
validation process

It would be great if you could elaborate on that; v2.2 is meant to be compatible, so if you could provide me with a way to check it out or more details on what is breaking, I could see what I can do.

As you can guess, we won't support older versions so it's in your best interest to upgrade at some point...

**Comment by tiimbz** [comment]
> It would be great if you could elaborate on that; v2.2 is meant to be compatible, so if you could provide me with a way to check it out or more details on what is breaking, I could see what I can do.

When upgrading from v2.0.7 to v2.2 the Parsley.remote validation breaks. Other validations work fine, it's just remote that seems to get skipped. When submitting the form, the form does its normal validation like parsley-required, but no parsley-remote request is fired to the server. 

This is the code:
```
<input type="text" id="proton-id-val" name="protonid" class="form-control"
       data-parsley-trigger="focusout"
       data-parsley-errors-container="#proton-id-error"
       data-parsley-remote-reverse="true"
       data-parsley-remote="http://api.domain.com/api/validate/proton_id"
       data-parsley-remote-message="Taken"
       data-parsley-required-message="Required"
       required/>
```

**Comment by marcandre** [comment]
>  no parsley-remote request is fired to the server

Oh my :bomb:  I'll fix that ASAP (tonight probably).

**Comment by marcandre** [comment]
So I had trouble investigating because or [#956]. This hasn't changed though, so should not be a difference.

That said, the request is sent. Here's [a fiddle that works](http://jsfiddle.net/marcandre/ke8ebpcp/), based on your code....

Be sure to have your console open before your field gets the focus, though, coz with your trigger, and *the fact that Parsley caches requests*, you might not see a request when you expect one...

**Comment by marcandre** [comment]
Just to be clear @tiimbz, I'd be very grateful if you could confirm you actually see a difference between 2.1 and 2.2, and if so, tell me more about it because it is meant to be compatible.

**Comment by tiimbz** [comment]
@marcandre Your fiddle indeed worked without any issues. The moment I replaced parsley.remote.js from v2.1.3 to v2.2.0 in our app, all AJAX calls broke. 

I was able to get everything working again by switching the order of which parsley.js and parsley.remote.js were loaded. Our app loads parsley.remote.js **BEFORE** loading parsley.js (as described in the documentation), but the problem disappeared by loading parsley.remote.js **AFTER** parsley.js. 

On topic: I could finally test this version against this bug #916 , and can confirm that with 2.2 indeed fixes it :) The error message is not hidden anymore on pressing Enter, and stays visible like it should, just like with clicking submit.

**Comment by marcandre** [comment]
You're supposed to load either `parsley`, or `parsley.remote`, not both :smile:

We'll probably merge them very soon, so confusion will disappear.

I'm thus closing this, will reopen if there's additional issues. Thanks!

**Comment by tiimbz** [comment]
> You're supposed to load either parsley, or parsley.remote, not both :smile:

Maybe good to also update the documentation on to reflect this? 

From http://parsleyjs.org/doc/index.html#remote: "To use this plugin, either load parsley.remote.js before loading parsley.js, or directly load parsley.remote.js."

**Comment by marcandre** [comment]
Indeed, I tweaked the doc, thanks

**Pull request closed without merging**
