### PR TITLE
Added Norwegian localization

### PR DESCRIPTION
**Pull request by torryt**

### CODE REVIEW

**Comment by guillaumepotier** [comment]
Hi @torryt thanks for the PR!

Could you please squash your commits before I merge it?

Thanks a lot

Best

**Comment by marcandre** [comment]
Thanks for this PR :smile:

Could you squash your commits, as one is just a fix for the other?

**Comment by torryt** [comment]
Sorry about that.
Commits squashed!

**Comment by marcandre** [comment]
lol, there was some echo there :smile:

Merged! Thanks again for the PR

**Comment by guillaumepotier** [comment]
[echo mode ON] Thanks :) [echo mode OFF]

**Pull request merged**
