### PR TITLE
Fix for sending of `FormData` by falling back to not using the Parsley remote cache

### PR DESCRIPTION
**Pull request by papiro**

### CODE REVIEW

**Comment by papiro** [comment]
As part of this pull-request, an update to the documentation on the `field.validate` method was made.  It doesn't return false, but rather returns an array of validation errors.

**Comment by papiro** [comment]
It's difficult for me to overcome the failure in the Travis build because just to try fixes, I have to make commits and push.  If I run the same commands Travis is running locally, I get a different result.  I'm stuck right now, without removing the reference to `FormData` from the test.

**Comment by ankurk91** [comment]
I would love if this PR can be merge.

**Comment by marcandre** [comment]
Mmm, sorry never commenting on this PR.

There are a couple of things going on, none of which seem clear to me.
1) useCache: what is the usecase?
2) Not too sure what's going on with `FormData`
3) Change of API for `validate`

Moreover the PR also changes `dist/`.

Because of this, I will close this and ask @papiro, @ankurk91 or anyone else to open a separate issue/PR for any of these changes that they would like to see (and why). Thanks.

**Comment by papiro** [comment]
It's one year later and i had trouble remembering the issue i was having, but reading the commit messages made it clear to me.  Thankfully i wrote detailed commit messages!

**Comment by marcandre** [comment]
@papiro Part of the conversation in #1067. Also see [this custom validator](http://parsleyjs.org/doc/examples/customvalidator.html) that deals with `FormData` client-side.

**Pull request closed without merging**
