### PR TITLE
update Babel to the latest version

### PR DESCRIPTION
**Pull request by geosigno**
Babel has been updated to the latest version to avoid issue when compiling. ([#1261](https://github.com/guillaumepotier/Parsley.js/issues/1261))

### CODE REVIEW

**Comment by marcandre** [comment]
Thanks for the PR :-)

I'm not sure why, but this has the same issue as #1170, namely that in case there is no `exports` or `define` (such as a browser), the code that loads it all changes from

```
(function (global, factory) {
  global.parsley = factory(global.jQuery);
})(this, function ($) {
```
to
```
(function (global, factory) {
  global.parsley = factory(global.jQuery);
})(undefined, function ($) {
```

So instead of doing `window.parsley = factory(window.jQuery)` (since `this` at the top level of browser is `window`), the new code does `undefined.parsley = factory(undefined.jQuery)` which won't work...

**Comment by geosenna** [comment]
help needed

**Comment by marcandre** [comment]
Ok, I'm looking into this.

**Comment by marcandre** [comment]
I've spent hours so far trying to update this. It is really painful.

Progress so far: #1267

**Comment by marcandre** [comment]
Merged in master

**Pull request closed without merging**
