### PR TITLE
Fixed multiple language support

### PR DESCRIPTION
**Pull request by jontorrado**
The correct way of adding multiple langs is with the ParsleyValidator

### CODE REVIEW

**Comment by marcandre** [comment]
Actually, the correct way is via `Parsley`. I want to get rid of all other constants than `Parsley` :smile:...

**Comment by jontorrado** [comment]
window.Parsley gives an error when installing via bower. This error gets
fixed when using window.ParsleyValidator

**Comment by marcandre** [comment]
Are you using `2.2.0rc4`?

**Comment by jontorrado** [comment]
No, latest 1.7 stable.

**Comment by marcandre** [comment]
Please update :smile: Just released `2.2.0` today.

**Comment by jontorrado** [comment]
Hi there,

I looked to the wrong number. I am using 2.1.3.

Kind regards.

**Comment by marcandre** [comment]
Answer is the same though... Please update :smile: Just released 2.2.0 today.

**Pull request closed without merging**
