### PR TITLE
Update to babel 6

### PR DESCRIPTION
**Pull request by gempi**
- Update to babel 6

### CODE REVIEW

**Comment by marcandre** [comment]
Merged, thanks!
After a couple of tweaks, all look good with newer Babel.

**Comment by marcandre** [comment]
Grrr, that broke the build. The jquery loading it builds looks like:
```
(typeof exports === 'undefined' ? 'undefined' : _typeof(exports)) === 'object' && typeof module !== 'undefined' ? module.exports = factory(require('jquery')) : typeof define === 'function' && define.amd ? define(['jquery'], factory) : global.parsley = factory(global.jQuery);
})(undefined, function ($)
```

Instead of
```
// ...
}(this, function ($)
```

Reverted the commit

**Comment by Geddo** [comment]
Any news on that?

**Comment by marcandre** [comment]
I'm personally not investigating...

**Comment by geosenna** [comment]
+1

**Comment by marcandre** [comment]
I'm looking into this.

**Comment by marcandre** [comment]
I've spent hours so far trying to update this. It is really painful.

Progress so far: #1267

**Pull request merged**
