### PR TITLE
Fix jshint error

### PR DESCRIPTION
**Pull request by vsn4ik**
http://api.jquery.com/jquery.noop/

### CODE REVIEW

**Comment by vsn4ik** [comment]
Travis CI complete the task without errors.

**Comment by marcandre** [comment]
The whitespace and semicolons could be ok, the `$.noop` is not acceptable as we then go on modifying it's prototype. I don't want to mess with `$.noop`!

In any case, the fact that `ParsleyAbstract`'s construction is empty is true for now, could be changed in the future.

**Comment by vsn4ik** [comment]
`$.noop` removed.

**Comment by marcandre** [comment]
Awesome, thanks for the PR :+1:

We should include that in the test suite.

**Pull request merged**
