### PR TITLE
2.1

### PR DESCRIPTION
**Pull request by guillaumepotier**

### CODE REVIEW

**Comment by guillaumepotier** [comment]
Rebased with `master`.

**Comment by marcandre** [comment]
As far as I'm concerned, #808 and #809 are the only things needed to complete the v2.1 release.
I'd still appreciate some feedback on the ideas of #816, but even if positive I don't think we should wait for that to release 2.1

**Comment by guillaumepotier** [comment]
#816 could be a nice last feature / rework to add to 2.1. It would change some behaviors (especially with javascript and dom binded options priority) and could really fits in this release.

Maybe we could do for the first time a release candidate and inform the subscribed to the newsletter to encourage them to test 2.1 before it is fully released as stable? (Especially with #809 that could impact performances on large forms / heavy dom).

Meanwhile I'm going to release a 2.0.7 version of master. What do you think?

Best

**Comment by marcandre** [comment]
Sure, sounds like a plan.
In any case, could you rebase off master?

**Comment by guillaumepotier** [comment]
I've rebased `2.1`. Should we build and tag here a `2.1.0-rc1` version?

**Comment by marcandre** [comment]
Sounds good!

**Comment by guillaumepotier** [comment]
Mergin 2.1 while it's hot. Planning to release this week.

**Pull request merged**
